### PR TITLE
update runtime org.gnome.Platform (from 46) to 47

### PR DESCRIPTION
**Pull request by zWhdmB5T**
update runtime org.gnome.Platform (from 46) to 47

### CODE REVIEW

**Comment by OzarkShepherd** [comment]
@zWhdmB5T thank you for your contribution. Gnome 47 uses python 3.12, which appears to be incompatible with the abandoned goocanvas project required for the graphview addon to work. I am testing to see if the last Goocanvas release (version 3 which did not work in the flatpak last time I tried in 2021) will work now. https://github.com/OzarkShepherd/flatpak/tree/flathubPR%2329 If Goocanvas 3 won't work, then I will have to ask the developers at the Gramps Project discourse to find a workaround for the Goocanvas requirement in Graphview, or we will have delay the Gnome 47 upgrade until Gnome 46 is end of life in March 2025.  In the latter case, we would have to drop Graphview addon support in the flatpak since goocanvas would no longer work with the version of python available in Gnome.

**Comment by OzarkShepherd** [comment]
It looks like 2 patches for Goocanvas 3 and an additional patch for Goocanvas 2 might make Goocanvas work with python 3.12.  https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c611f2e0d7b4e2eae1a3ccf177b69e61683b942d
I don't feel like going through the process of troubleshooting errors and then verifying that the flatpak builds actually work right now. We still have until March and I have health problems. I would be grateful if you could figure it out.

**Comment by zWhdmB5T** [comment]
@OzarkShepherd What a pity to hear about your situation. I am sorry to say that I am not into coding: I would like to do that but I cannot (I don't have the skills). I just recently set up PRs for some FlatPaks I use to update the runtime: in some cases it worked, in some cases id did not. But I am swamped by eventual error messages (if not obvious ones).

**Comment by zWhdmB5T** [comment]
So, I formally close this PR due to reasons for this time.

**Pull request closed without merging**
