### PR TITLE
Exiv2 updates and various improvements

### PR DESCRIPTION
**Pull request by hfiguiere**
It started with and exiv2 update, but other problem arose:

- use the desktop file from upstream, the one provided was invalid (empty Exec)
- use intltool from shared-modules, it carries patches
- export the mime types. Icons need to be handled too, it's a bit more complicated, but this already allow open Gramps document from the file manager
- resynced the appadata with upstream. Ultimately 1. it should be handled through a patch 2. the changes for non validation should be submitted upstream (~~missing release, incorrect license and~~ app-id) **Update:** some of these are already upstream. 
- removed an unecessary CLI option for python during build that was x86_64 specific anyway.

### CODE REVIEW

**Review by OzarkShepherd — COMMENTED** [review]
Thank you so much for the Exiv2 updates.  Gramps Project likes to look at flatpak changes at their github before they get pushed to flathub, so would you mind making a pull request at https://github.com/gramps-project/flatpak ?  I don't want to steal your contributions by submitting them at their github myself.

**Comment by OzarkShepherd** [comment]
I submitted a modified version of this pull request to Gramps Project for their review https://github.com/gramps-project/flatpak/pull/21 with a couple changes.  It will be left up about a week to give them time to look at it.
1. I updated the manifest note on exiv2 to show revision date
2. Since intltool in shared modules is the same version number as the intltool already being used in the Gramps flatpak, I didn't want to set up git on my current system to submit the shared modules version to Gramps Project when it won't be a significant difference anyway.

**Comment by hfiguiere** [comment]
it's failing because you deleted the `.gitmodules`

**Comment by OzarkShepherd** [comment]
> it's failing because you deleted the `.gitmodules`

Yes, I don't know github well enough to either get rid of the shared modules directory or to roll back the deletion of .gitmodules

**Pull request merged**
